import PDFDocument from 'pdfkit';

export const generateBillPDF = (bill, store) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(store.pharmacyName || 'PharmaAssist', { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(9).font('Helvetica').text(store.exactAddress || '', { align: 'center' });
      doc.text(`Phone: ${store.phone || ''} | License: ${store.drugLicenseNumber || 'N/A'}`, { align: 'center' });

      // Divider
      doc.moveDown(0.5);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#333333');
      doc.moveDown(0.5);

      // Bill info
      doc.fontSize(10).font('Helvetica-Bold').text(`Bill No: ${bill.billNumber}`);
      doc.font('Helvetica').text(`Date: ${new Date(bill.createdAt).toLocaleString('en-BD', { dateStyle: 'long', timeStyle: 'short' })}`);
      doc.moveDown(0.3);

      if (bill.patient) {
        doc.font('Helvetica-Bold').text(`Patient: ${bill.patient.fullName || 'N/A'}`);
        doc.font('Helvetica').text(`Phone: ${bill.patient.phone || 'N/A'}`);
      } else if (bill.walkInCustomer?.name) {
        doc.font('Helvetica-Bold').text(`Customer: ${bill.walkInCustomer.name}`);
        if (bill.walkInCustomer.phone) doc.font('Helvetica').text(`Phone: ${bill.walkInCustomer.phone}`);
      } else {
        doc.font('Helvetica-Oblique').text('Walk-in Customer');
      }

      // Table header
      doc.moveDown(0.8);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#333333');
      doc.moveDown(0.3);

      const tableTop = doc.y;
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('#', 45, tableTop, { width: 25 });
      doc.text('Medicine', 70, tableTop, { width: 200 });
      doc.text('Qty', 280, tableTop, { width: 40, align: 'center' });
      doc.text('Price', 330, tableTop, { width: 70, align: 'right' });
      doc.text('Disc%', 410, tableTop, { width: 50, align: 'center' });
      doc.text('Total', 470, tableTop, { width: 80, align: 'right' });

      doc.moveDown(0.5);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#cccccc');
      doc.moveDown(0.3);

      // Items
      doc.font('Helvetica').fontSize(9);
      bill.items.forEach((item, idx) => {
        const y = doc.y;
        doc.text(`${idx + 1}`, 45, y, { width: 25 });
        doc.text(`${item.medicineName || 'Medicine'} ${item.strength || ''}`, 70, y, { width: 200 });
        doc.text(`${item.quantity}`, 280, y, { width: 40, align: 'center' });
        doc.text(`${item.unitPrice.toFixed(2)}`, 330, y, { width: 70, align: 'right' });
        doc.text(`${item.discountPercentage || 0}%`, 410, y, { width: 50, align: 'center' });
        doc.text(`${item.lineTotal.toFixed(2)}`, 470, y, { width: 80, align: 'right' });
        doc.moveDown(0.6);
      });

      // Totals
      doc.moveDown(0.3);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#333333');
      doc.moveDown(0.5);

      doc.font('Helvetica').fontSize(10);
      const subtotalY = doc.y;
      doc.text(`Subtotal:`, 370, subtotalY, { width: 100, align: 'right' });
      doc.text(`${bill.subtotal.toFixed(2)} BDT`, 470, subtotalY, { width: 80, align: 'right' });

      if (bill.totalDiscount > 0) {
        doc.moveDown(0.4);
        const discountY = doc.y;
        doc.text(`Discount:`, 370, discountY, { width: 100, align: 'right' });
        doc.text(`-${bill.totalDiscount.toFixed(2)} BDT`, 470, discountY, { width: 80, align: 'right' });
      }

      doc.moveDown(0.4);
      doc.moveTo(370, doc.y).lineTo(555, doc.y).stroke('#333333');
      doc.moveDown(0.4);

      doc.font('Helvetica-Bold').fontSize(12);
      const grandTotalY = doc.y;
      doc.text(`GRAND TOTAL:`, 370, grandTotalY, { width: 100, align: 'right' });
      doc.text(`${bill.grandTotal.toFixed(2)} BDT`, 470, grandTotalY, { width: 80, align: 'right' });

      doc.moveDown(0.6);
      doc.font('Helvetica').fontSize(9).text(`Payment: ${bill.paymentMethod}`, 370, doc.y, { align: 'right' });

      // Notes
      if (bill.notes) {
        doc.moveDown(1);
        doc.font('Helvetica-Oblique').fontSize(9).text(`Note: ${bill.notes}`, 45);
      }

      // Footer
      doc.moveDown(2);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#cccccc');
      doc.moveDown(0.5);
      const footerMsg = store.billSettings?.footerMessage || 'Thank you for choosing our pharmacy!';
      doc.font('Helvetica').fontSize(8).text(footerMsg, { align: 'center' });
      doc.text('Generated by PharmaAssist', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};